apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prom-pv 
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /volume1/k8s
    server: 192.168.1.3
    readOnly: false

