apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nmap-scanner
spec:
  schedule: "45 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nmap
            image: networkstatic/nmap
            args:
            - -sT
            - 192.168.1.1-200
          restartPolicy: Never
