apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ssh-scanner
spec:
  schedule: "45 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ssh-scanner
            image: mozilla/ssh_scan 
            args:
            - /app/bin/ssh_scan 
            - -t
            - 192.168.1.1/24
          restartPolicy: Never
