apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pihole-config
  namespace: pihole
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8s/pihole/pihole
    server: 192.168.1.3
    readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pihole-dnsmasq
  namespace: pihole
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8s/pihole/dnsmasq.d
    server: 192.168.1.3
    readOnly: false

