apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pihole-config 
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pihole-dnsmasq
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
