---
apiVersion: v1
kind: Namespace
metadata:
  name: splunk

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: splunk
  name: splunk
  namespace: splunk
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: splunk
  strategy: {}
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - image: splunk/splunk:latest
        name: splunk 
        resources: {}
        ports:
          - name: web
            containerPort: 8000
            protocol: TCP
          - name: forward
            containerPort: 9997
            protocol: TCP
          - name: hec
            containerPort: 8088
            protocol: TCP
          - name: udp-syslog
            containerPort: 9999
            protocol: UDP
          - name: tcp-syslog
            containerPort: 9999
            protocol: TCP
        volumeMounts:
          - mountPath: /opt/splunk/var/
            name: splunk-volume-var
          - name: splunk-volume-etc
            mountPath: /opt/splunk/etc
          - name: log-volume
            mountPath: /var/log
        env:
          - name: SPLUNK_START_ARGS
            valueFrom:
              configMapKeyRef:
                name: splunk-map
                key: start_args
          - name: SPLUNK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: splunk-pass
                key: password
          - name: SPLUNK_HOME
            value: /opt/splunk
          - name: DEBUG
            value: "true"
        volumeMounts:
        - mountPath: /opt/splunk/etc
          name: splunk-volume-etc
      volumes:
      - name: splunk-volume-var
        persistentVolumeClaim:
          claimName: pvc-splunk-var
      - name: splunk-volume-etc
        persistentVolumeClaim:
          claimName: pvc-splunk-etc
      - name: log-volume
        persistentVolumeClaim:
          claimName: pvc-varlog-local

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-map
  namespace: splunk
data:
  start_args: "--accept-license"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: splunk
  labels:
    app: splunk
  name: splunk-tcp
  namespace: splunk
spec:
  loadBalancerIP: 192.168.2.246
  externalTrafficPolicy: Local
  ports:
  - name: web-svc
    port: 8000
    protocol: TCP
    targetPort: web
  - name: forward-svc
    port: 9997
    protocol: TCP
    targetPort: forward
  - name: hec-svc
    port: 8088
    protocol: TCP
    targetPort: hec
  - name: tcp-syslog-svc
    port: 9999
    protocol: TCP
    targetPort: tcp-syslog
  selector:
    app: splunk
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: splunk
  labels:
    app: splunk
  name: splunk-udp
  namespace: splunk
spec:
  loadBalancerIP: 192.168.2.246
  externalTrafficPolicy: Local
  ports:
  - name: udp-syslog-svc
    port: 9999
    protocol: UDP
    targetPort: udp-syslog
  selector:
    app: splunk
  type: LoadBalancer


