---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-splunk-var
  namespace: splunk
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/splunk/data/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-worker2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-splunk-etc
  namespace: splunk
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/splunk/etc/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-worker2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-varlog-local
  namespace: splunk
spec:
  storageClassName: "log-storage"
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/var/log/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-worker2"
