apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-unifi
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8s/unifi-controller
    server: 192.168.1.3
    readOnly: false

