apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cmk
  namespace: cmk
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/k8s/check_mk
    server: 192.168.1.3
    readOnly: false

