apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-pvc 
  namespace: cmk
spec:
  storageClassName: nfs-client
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
